python sevira_no_word2vec_bbc.py Word2Vec 2
python sevira_no_word2vec_bbc.py Word2Vec 3
python sevira_no_word2vec_bbc.py Word2Vec 4
python sevira_no_word2vec_bbc.py Word2Vec 5
python sevira_no_word2vec_bbc.py Word2Vec 6
python sevira_no_word2vec_bbc.py Word2Vec 7
python sevira_no_word2vec_reuters.py Word2Vec 2
python sevira_no_word2vec_reuters.py Word2Vec 3
python sevira_no_word2vec_reuters.py Word2Vec 4
python sevira_no_word2vec_reuters.py Word2Vec 5
python sevira_no_word2vec_reuters.py Word2Vec 6
python sevira_no_word2vec_reuters.py Word2Vec 7