ipython solta_o_som_reuters.py Binario 0.1
ipython solta_o_som_reuters.py Binario 0.4
ipython solta_o_som_reuters.py Binario 0.7
ipython solta_o_som_reuters.py TF 0.1
ipython solta_o_som_reuters.py TF 0.4
ipython solta_o_som_reuters.py TF 0.7
ipython solta_o_som_reuters.py TFIDF 0.1
ipython solta_o_som_reuters.py TFIDF 0.4
ipython solta_o_som_reuters.py TFIDF 0.7